name: Check Links and Generate JSON

on:
  schedule:
    - cron: '0 1 * * *'
    - cron: '0 13 * * *'
  workflow_dispatch:

env:
  TZ: Asia/Shanghai

jobs:
  check_links:
    runs-on: ubuntu-latest

    steps:
    - name: Pull latest repository
      uses: actions/checkout@v4

    - name: Cache pip packages
      uses: actions/cache@v4
      with:
        path: ~/.cache/pip
        key: ${{ runner.os }}-pip-${{ hashFiles('**/requirements.txt') }}
        restore-keys: |
          ${{ runner.os }}-pip-

    - name: Install python
      uses: actions/setup-python@v5
      with:
        python-version: '3.12'

    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install -r requirements.txt

    # -----------------------------
    # 下载上次 result.json artifact
    # -----------------------------
    - name: Download result.json artifact
      uses: dawidd6/action-download-artifact@v6
      with:
        github_token: ${{secrets.GITHUB_TOKEN}}
        branch: main
        name: 'result_json'
        path: './'
        if_no_artifact_found: warn

    # -----------------------------
    # 运行 main.py，生成 result.json
    # -----------------------------
    - name: Run Python script to check friend-links
      env:
        PROXY_URL: ${{ secrets.PROXY_URL }}
        SOURCE_URL: ${{ secrets.SOURCE_URL }}
      run: |
        echo "SOURCE_URL: $SOURCE_URL"
        python main.py

    # -----------------------------
    # 上传 result.json artifact
    # -----------------------------
    - name: Upload result.json as artifact
      uses: actions/upload-artifact@v4
      with:
        name: 'result_json'
        path: './result.json'
        retention-days: 10

    # -----------------------------
    # 推送 result.json 到 static/
    # -----------------------------
    - name: Commit and push result.json
      run: |
        cp ./result.json static/
        cd static
        git init
        git add result.json
        git commit -m "⏱️GitHub Action每日更新 result.json"
        git push --force https://x-access-token:${{ secrets.GITHUB_TOKEN }}@github.com/${{ github.repository }}.git HEAD:page

    # -----------------------------
    # 运行 main1.py，生成 projects_status.json
    # -----------------------------
    - name: Run main1.py
      run: python main1.py

    # 上传 projects_status.json artifact
    - name: Upload projects_status.json as artifact
      uses: actions/upload-artifact@v4
      with:
        name: 'projects_status_json'
        path: './projects_status.json'
        retention-days: 10

    # 推送 projects_status.json 到 static/
    - name: Commit and push projects_status.json
      run: |
        cp ./projects_status.json static/
        cd static
        git init
        git add projects_status.json
        git commit -m "⏱️GitHub Action每日更新 projects_status.json"
        git push --force https://x-access-token:${{ secrets.GITHUB_TOKEN }}@github.com/${{ github.repository }}.git HEAD:page

    # -----------------------------
    # 删除老的 workflow runs
    # -----------------------------
    - name: Delete Workflow Runs
      uses: Mattraks/delete-workflow-runs@v2
      with:
        retain_days: 30
        keep_minimum_runs: 6

  keepalive-workflow:
    name: Keepalive Workflow
    if: ${{ always() }}
    needs: check_links
    runs-on: ubuntu-latest
    permissions:
      actions: write
    steps:
      - uses: liskin/gh-workflow-keepalive@v1
